- perf-tool/include/serverClients.hpp
- perf-tool/src/agent.cpp
- perf-tool/src/client.cpp
- perf-tool/src/monitor.cpp
1. Use the same default port number for both server and client
2. Small cleanup for option processing
3. Add critical section for updating map with number of contention samples per object type
> Fixes for perf-tool agent

- perf-tool/include/monitor.hpp
- perf-tool/src/agentOptions.cpp
- perf-tool/src/monitor.cpp
Added new command option: "stackTraceDepth": N
If the value of the stackTraceDepth is larger than 0
the agent will collect N frames starting with the
method where monitor contention was detected.
Also, changed the behavior so that for a sample rate M
larger than 1 the agent will report only the M-th sample.
> Add improvements to monitor contention functionality

- perf-tool/include/infra.hpp
- perf-tool/src/agent.cpp
- perf-tool/src/agentOptions.cpp
- perf-tool/src/infra.cpp
- perf-tool/src/monitor.cpp
This commit gives the application the ability to register a
callback function with the agent, such that when an event is
triggered and data collected, that data is sent to the application
through the callback.
To accomodate this change the structure of a command changed
to allow the "callback" keyword, which will define the class,
method name and signature of the callback.
Example:
{
"functionality": "monitorEvents",
"callback": {
"class": "T",
"method": "callback",
"signature": "(Ljava/lang/String;)V"
}
}
The commit also implements some code restructuring to introduce
a `class EventConfig` which will be used to store (and cache)
information about each type of event that is monitored.
> Implement app callback feature

- perf-tool/src/serverClients.cpp
The current timestamp employed in the data has
second's granularity, which can be too restrictive
in many cases - for example in a high contention
case, many sections may be seen as having the same
timestamp. Convert time into nanosecond precision.
before:
"timestamp": 1608336000
after:
"timestamp": 1614073053488102314
Fixes: https://github.com/eclipse/openj9-utils/issues/19
Signed-off-by: Gireesh Punathil gpunathi@in.ibm.com
> perf-tools: make timestamps nanosecond granular

- perf-tool/src/monitor.cpp
When an app is profiled over a time period,
a number of sections are produced, potentially
for the same lock. However, there is no key
field in the JSON data that help us to associate
those together.
Add a "head" field with the hashcode of the object
which is the current subject of contention. According
to the JVMTI spec, the hashcode is guarenteed to be
unique throughout its life span.
From the doc:
```
jvmtiError
GetObjectHashCode(jvmtiEnv* env,
jobject object,
jint* hash_code_ptr)
For the object indicated by object, return via hash_code_ptr a hash code. 
This hash code could be used to maintain a hash table of object references, 
however, on some implementations this can cause significant performance
impacts--in most cases tags will be a more efficient means of associating
information …
```
> add a head field with object hashcode

- perf-tool/include/infra.hpp
- perf-tool/include/monitor.hpp
- perf-tool/src/agent.cpp
- perf-tool/src/agentOptions.cpp
- perf-tool/src/infra.cpp
- perf-tool/src/monitor.cpp
Prints the current and owner thread details i.e threadname
threadId and nativethreadId in MonitorContendedEnter Event
Fixes: #20
Fixes: #38
> Added MonitorContendedEnter event

- perf-tool/include/infra.hpp
- perf-tool/src/agent.cpp
- perf-tool/src/agentOptions.cpp
- perf-tool/src/infra.cpp
- perf-tool/src/monitor.cpp
- perf-tool/src/verboseLog.cpp
This commit adds JLM (Java Lock Monitor) support to the
OpenJ9 Perf Agent. The new command must look like this:
{
"delay": 1,
"functionality": "jlm"
}
At the moment, the only option that could be sent with this
command is the "delay". All other keywords will be ignored.
Typically, the user sends a "start" command for the "jlm"
functionality and, after a while (specified by the delay),
sends a "stop" command. E.g.:
{
"command": "stop",
"delay": 10,
"functionality": "jlm"
}
Once the stop command is received, the agent will ask the JVM
to send a JLM dump which contains information about all the
monitors in the JVM. The agent parses that dump and creates
a more readable output encoded as json. In this output, the
monitors that were not acquired at least once will be …
> Implement JLM support in the perf agent

- perf-tool/include/infra.hpp
- perf-tool/include/server.hpp
- perf-tool/include/serverClients.hpp
- perf-tool/src/exception.cpp
- perf-tool/src/infra.cpp
- perf-tool/src/methodEntry.cpp
- perf-tool/src/monitor.cpp
- perf-tool/src/objectalloc.cpp
- perf-tool/src/perf.cpp
- perf-tool/src/server.cpp
- perf-tool/src/serverClients.cpp
- perf-tool/src/verboseLog.cpp
In the generated output of the perf-tool,
there can be many sections based on the input
configuration. Even though each sections have
different set of key-valus from which the section
can be identified, it is desirable to have an
eventType key, for easy consumption.
I have covered all the handlers implemented so far.
Fixes: https://github.com/eclipse/openj9-utils/issues/35
Signed-off-by: Gireesh Punathil <gpunathi@in.ibm.com>
> add event types

- perf-tool/include/methodEntry.hpp
- perf-tool/src/agent.cpp
- perf-tool/src/agentOptions.cpp
- perf-tool/src/methodEntry.cpp
- perf-tool/src/monitor.cpp
In order to enable method tracing we need to set the
`can_generate_method_entry_events` capability. For some
reason this capability can be enabled only during the
OnLoad phase. Therefore, the agent must be loaded from
the very beginning, and late attach will not do.
This commit also adds the ability to print the stack trace
up to the specified depth.
Examples of commands:
```
{
"functionality": "methodEntryEvents",
"delay": 1,
"stackTraceDepth": 5
},
{
"functionality": "methodEntryEvents",
"command": "stop",
"delay": 5
}
```
> Fix MethodEnter support for Perf Agent

- perf-tool/src/monitor.cpp
In monitorContendedEnter we are sending data
to server twice after getting owner thread info
and current thread info. Fixed that by removing
one after Owner info
Signed-Off-by: Ravali Yatham <rayatha1@in.ibm.com>
> fix event-type in monitorContendedEnter

- perf-tool/src/agentOptions.cpp
- perf-tool/src/monitor.cpp
perf-tool: add value to count per object monitor_contended data of logs.json
fixes: https://github.com/eclipse/openj9-utils/issues/28
Signed-off-by: PoojaDurgad <Pooja.D.P@ibm.com>
> Add value to count per object monitor_contended data

- perf-tool/include/methodEntry.hpp
- perf-tool/src/agent.cpp
- perf-tool/src/agentOptions.cpp
- perf-tool/src/methodEntry.cpp
This event is very much similar to the MethodEnter event.
Example of commands to enable/disable:
```
{
"functionality": "methodExitEvents",
"delay": 1,
"stackTraceDepth": 3
},
{
"functionality": "methodExitEvents",
"command": "stop",
"delay": 3
}
```
Example of output:
```
{
"body": {
"methodClass": "Ljava/lang/String;",
"methodName": "lengthInternal",
"methodNum": 5908,
"methodSig": "()I",
"stackTrace": [
{
"class": "Ljava/lang/String;",
"method": "lengthInternal",
"signature": "()I"
},
{
"class": "Ljava/lang/String;",
"method": "length",
"signature": "()I"
},
{
"class": "Ljava/lang/String;",
"method": "indexOf",
"signature": "(Ljava/lang/String;I)I"
}
]
},
"eventType": "methodExitEvent",
"from": "Server",
"timestamp": 1616194905999605293
},
```
Signed-off-by: Marius …
> Implement methodExit event in perf agent

- perf-tool/src/agent.cpp
avoid process crashes for non-existent command file.
fixes: https://github.com/eclipse/openj9-utils/issues/33
Signed-off-by: PoojaDurgad <Pooja.D.P@ibm.com>
> perf-tool: fix process crashes.

- perf-tool/include/infra.hpp
- perf-tool/src/agentOptions.cpp
- perf-tool/src/infra.cpp
- perf-tool/src/methodEntry.cpp
Since methodEnter/Exit hooks can generate very many events
it may usefull to have some way of requesting such events
only for some classes/methods. This commit implements such
a filtering scheme.
Syntax of a command:
{
"functionality": "methodEntryEvents",
"delay": 0,
"stackTraceDepth": 3,
"filter": {
"class": "LMyThread;",
"method": "syncRegion",
"signature": "\\(I\\)"
}
The matching for the "filter" class, method name and signature is
done using ECMAScript grammar: http://www.cplusplus.com/reference/regex/ECMAScript
Note that parenthesis must be escaped twice (using \\): once for
the JSON and one for regular expressions inside C++ code.
Square brackets and dollar sign which are typical used in Java class naming
also needs to be escaped.
Signed-off-by: Marius Pirvu …
> Add filtering capability to methodEnter/Exit events

- perf-tool/src/agentOptions.cpp
- perf-tool/src/monitor.cpp
Calculates how much time thread waited
to acquire the monitor
> Compute lockLatency

- perf-tool/include/serverClients.hpp
- perf-tool/src/agent.cpp
- perf-tool/src/serverClients.cpp
fix process crash for non existent command file in headless mode and commands in interactive mode.
fixes: https://github.com/eclipse/openj9-utils/issues/33
Signed-off-by: PoojaDurgad <Pooja.D.P@ibm.com>
> fix process crashes in interactive and headless mode.

- perf-tool/include/serverClients.hpp
- perf-tool/src/serverClients.cpp
While logging data to logFile use traditional
C FILE operations instead of streams
> Avoid using streams

- perf-tool/README.md
- perf-tool/src/agent.cpp
- perf-tool/src/infra.cpp
Since method enter/exit tracing capability can interfere
with the JIT compiler optimizer, it's better to turn off
this capability by default, but allow the user to turn it
on, if she wants to use it.
This commit adds a new option for the agent called:
`methodEnterCapability` with two possible values "on" or "off".
The default is "off".
Note that enabling method enter/exit tracing capability does
not enable tracing itself. Starting/stopping the tracing
needs to be done with json commands like with any other tracing.
Fixes: #57
> Add option to turn on/off method enter/exit capability

- perf-tool/include/server.hpp
- perf-tool/src/infra.cpp
- perf-tool/src/server.cpp
If tracing of an event is enabled while the JVM shuts down,
a crash can happen because the `Server` object is destroyed,
while the tracing thread still wants to use this object.
This commit prevents crashes during shutdown by adding a lock.
When the `Server` object is used, the current thread will hold
a `serverMonitor` to prevent the thread executing the `VMDeath`
event from destroying the `Server` object. This will also prevent
the output from different tracing threads from being interleaved.
Fixes: #30
> Prevent crashes at JVM shutdown

- perf-tool/include/client.hpp
- perf-tool/src/client.cpp
- perf-tool/src/server.cpp
While starting the client pass port number and optional
--log file name to which data will be redirected and host.
Default log path is clientLogs.json
Eg: `./a.out --portNo=port --log=logname --host=localhost`
or use short notations as below:
`./a.out --p=port --l=logname --h=localhost`
Use -u for usage:
`./a.out -u`
Fixes: #67
> Redirect networking clients data to file

- perf-tool/src/verboseLog.cpp
We are collecting only nth sample of events which
results in missing sections within one gc cycle. So
reset samplerate to 1 even if user specifies sampleRate
greater than 1
Fixes: #41
> Avoid inconsistency in verbose data collection

- perf-tool/include/agentOptions.hpp
- perf-tool/include/server.hpp
- perf-tool/include/serverClients.hpp
- perf-tool/src/agentOptions.cpp
- perf-tool/src/server.cpp
- perf-tool/src/serverClients.cpp
This commit fixes a performance bug caused by a tight loop
that permanently checks whether there are delayed commands
to be processed. This bug does not show if we give the agent
a port option to listen to, because in that case the loop
mentioned above includes a poll operation with a timeout of 250ms.
This commit also makes the following changes:
- All commands coming for the command file are read during agent load
and inserted into a linked list sorted by the time when the
command needs to be applied
- Replaced the code that was always sorting the array of commands
(now we insert in the right place to keep the collection always sorted)
- Removed some of the functions that are no longer needed
- Removed some of the conversions from string to json and back
- Increased the poll timeout …
> Reduce performance overhead of perf agent 

- helm-chart/index.yaml
- helm-chart/openj9-jitserver-chart/Chart.yaml
- helm-chart/openj9-jitserver-chart/values.yaml
This PR updates the JITServer Helm Chart to 0.26 to follow OpenJ9 0.26 release. 
Binary Helm Chart: [openj9-jitserver-chart-0.26.0.tar.gz](https://github.com/eclipse-openj9/openj9-utils/files/6428928/openj9-jitserver-chart-0.26.0.tar.gz)
Reference: https://github.com/eclipse/openj9-utils/issues/46
Signed-off-by: Chris Chong <Zichun.Chong@ibm.com>
> JITServer Helm Chart for version upgrade to 0.26

- helm-chart/index.yaml
- helm-chart/openj9-jitserver-chart/values.yaml
Changed the image tag and the image PullPolicy to "IfNotPresent"
instead of "Always"
Binary Helm Chart:  [openj9-jitserver-chart-0.26.0.tar.gz](https://github.com/eclipse-openj9/openj9-utils/files/6709349/openj9-jitserver-chart-0.26.0.tar.gz)
Signed-off-by: Eman Elsabban <eman.elsaban1@gmail.com>
> Modified Image Tag and Image PullPolicy

- helm-chart/index.yaml
- helm-chart/openj9-jitserver-chart/templates/deployment.yaml
changed the args for JITServer in deployment.yaml to redirect
output to stdout and to file "output.log". Previously the output
was redirected to the file "output.log" only.
Binary Helm Chart: [openj9-jitserver-chart-0.26.0.tar.gz](https://github.com/eclipse-openj9/openj9-utils/files/6711865/openj9-jitserver-chart-0.26.0.tar.gz)
Signed-off-by: Eman Elsabban <eman.elsaban1@gmail.com>
> Modified the arguments for JITServer to redirect output

- helm-chart/index.yaml
- helm-chart/openj9-jitserver-chart/values.yaml
Binary Helm Chart: [openj9-jitserver-chart-0.26.0.tar.gz](https://github.com/eclipse-openj9/openj9-utils/files/6741630/openj9-jitserver-chart-0.26.0.tar.gz)
Signed-off-by: Eman Elsabban <eman.elsaban1@gmail.com>
> Modified the nodeAffinity to deploy the chart on Power Arch

- helm-chart/index.yaml
- helm-chart/openj9-jitserver-chart/Chart.yaml
- helm-chart/openj9-jitserver-chart/values.yaml
Binary Helm Chart: [openj9-jitserver-chart-0.27.0.tar.gz](https://github.com/eclipse-openj9/openj9-utils/files/7002653/openj9-jitserver-chart-0.27.0.tar.gz)
> Update JITServer HelmChart for OpenJ9 release 0.27

- helm-chart/index.yaml
- helm-chart/openj9-jitserver-chart/Chart.yaml
- helm-chart/openj9-jitserver-chart/values.yaml
[openj9-jitserver-chart-0.30.0.tar.gz](https://github.com/eclipse-openj9/openj9-utils/files/7981828/openj9-jitserver-chart-0.30.0.tar.gz)
> Update JITServer helm chart to OpenJ9 0.30.0

- helm-chart/openj9-jitserver-chart/README.md
This table is useful if the user wants to use the Helm chart
to deploy a JITServer instance for Java11/Java17 or for a different
release other than the most current one (saves him some time
searching through dockerhub).
> Add table with tags for ibm-semeru-runtimes images

- helm-chart/openj9-jitserver-chart/README.md
The readme file was brought up-to-date by
- Eliminating some references to AdoptOpenJDK
- Adding references to IBM Semeru Runtimes
- Mentioning that Java17 is supported too
Issue: #86
> Updates to the README.md file for the JITServer Helm Chart

- helm-chart/index.yaml
- helm-chart/openj9-jitserver-chart/Chart.yaml
- helm-chart/openj9-jitserver-chart/README.md
- helm-chart/openj9-jitserver-chart/values.yaml
- Update JITServer Helm chart to default to Java8 OpenJ9 release 0.33.1
- Increase the default memory request value to 1GB
- Change beta.kubernetes.io/arch to kubernetes.io/arch because the former is deprecated
- Update README with docker images OpenJ9 release 0.33.1 for Java8, 11 and 17
> Update JITServer Helm chart for OpenJ9 0.33.1

- helm-chart/index.yaml
- helm-chart/openj9-jitserver-chart/Chart.yaml
- helm-chart/openj9-jitserver-chart/README.md
- helm-chart/openj9-jitserver-chart/values.yaml
[openj9-jitserver-chart-0.36.0.tar.gz](https://github.com/eclipse-openj9/openj9-utils/files/10902590/openj9-jitserver-chart-0.36.0.tar.gz)
> Update JITServer Helm chart for OpenJ9 release 0.36.0

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- NOTICE.md
- SECURITY.md
CODE_OF_CONDUCT, SECURITY are copied from openj9.
CONTRIBUTING is copied from openj9 and modified.
NOTICE is derived from the example at
https://www.eclipse.org/projects/tools/documentation.php?id=technology.openj9
> Add CODE_OF_CONDUCT, CONTRIBUTING, NOTICE, SECURITY files

- helm-chart/index.yaml
- helm-chart/openj9-jitserver-chart/Chart.yaml
- helm-chart/openj9-jitserver-chart/README.md
- helm-chart/openj9-jitserver-chart/values.yaml
[openj9-jitserver-chart-0.40.0.tar.gz](https://github.com/eclipse-openj9/openj9-utils/files/12480493/openj9-jitserver-chart-0.40.0.tar.gz)
> Update JITServer Helm chart for OpenJ9 0.40.0

- helm-chart/index.yaml
- helm-chart/openj9-jitserver-chart/Chart.yaml
- helm-chart/openj9-jitserver-chart/README.md
- helm-chart/openj9-jitserver-chart/values.yaml
[openj9-jitserver-chart-0.44.0.tar.gz](https://github.com/user-attachments/files/17442088/openj9-jitserver-chart-0.44.0.tar.gz)
> Update JITServer Helm chart for OpenJ9 release 0.44.0

- helm-chart/index.yaml
- helm-chart/openj9-jitserver-chart/Chart.yaml
- helm-chart/openj9-jitserver-chart/README.md
- helm-chart/openj9-jitserver-chart/values.yaml
[openj9-jitserver-chart-0.46.1.tar.gz](https://github.com/user-attachments/files/17468202/openj9-jitserver-chart-0.46.1.tar.gz)
> JITServer Helm chart update for OpenJ9 release 0.46.1

- helm-chart/index.yaml
- helm-chart/openj9-jitserver-chart/Chart.yaml
- helm-chart/openj9-jitserver-chart/README.md
- helm-chart/openj9-jitserver-chart/values.yaml
[openj9-jitserver-chart-0.48.0.tar.gz](https://github.com/user-attachments/files/18001828/openj9-jitserver-chart-0.48.0.tar.gz)
> Update JITServer Helm chart for release 0.48.0

- helm-chart/index.yaml
- helm-chart/openj9-jitserver-chart/Chart.yaml
- helm-chart/openj9-jitserver-chart/README.md
- helm-chart/openj9-jitserver-chart/values.yaml
[openj9-jitserver-chart-0.49.0.tar.gz](https://github.com/user-attachments/files/19060308/openj9-jitserver-chart-0.49.0.tar.gz)
> Update JITServer Helm chart for release 0.49.0

- helm-chart/index.yaml
- helm-chart/openj9-jitserver-chart/Chart.yaml
- helm-chart/openj9-jitserver-chart/README.md
- helm-chart/openj9-jitserver-chart/values.yaml
[openj9-jitserver-chart-0.51.0.tar.gz](https://github.com/user-attachments/files/21319273/openj9-jitserver-chart-0.51.0.tar.gz)
> Update JITServer Helm chart for release 0.51.0
